### ISSUE TITLE
I can't use D-PAD on pro controller

### ISSUE THREAD

**Issue by FNOT** [ubergeek77/CCExtraGamepadOptions#2]
I can't use D-PAD on pro controller.
and also game shows me the button sprite different.
(ex : A > B, X > Y)
how can I solve this problem???

**Comment by ubergeek77** [comment]
Sorry, I'm not really supporting this mod anymore, but this isn't a problem with the mod anyway.

Your controller is sending A as B, and X as Y. This is common on 8BitDo controllers, you will have to remap it. For official Nintendo controllers, I'm not sure.

For the d-pad issue, I'm not sure either, but this mod touches nothing about that.

For both issues, try adding the game to Steam if it's not a Steam copy. Then once you have it on Steam, use Steam Input to map the buttons.

Caution: your save will crash on the vanilla game if this mod is removed. I don't have a permanent fix for this. See this issue for details:

https://www.github.com/ubergeek77/CCExtraGamepadOptions/issues/1
